// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  aboutMeSidebar: [{type: 'autogenerated', dirName: 'aboutMe'}],
  tilSidebar: [{type: 'autogenerated', dirName: 'til'}],
  projectSidebar: [
    {type: 'doc', id: 'project/index', label: 'Projects'},
    {
      type: 'category',
      label: 'Featured Work',
      collapsed: false,
      items: [
        {type: 'doc', id: 'project/road-test-100', label: 'Road Test 100'},
        {type: 'doc', id: 'project/shorts-pipeline', label: 'Shorts Pipeline'},
        {type: 'doc', id: 'project/shorts-source-radar', label: 'Shorts Source Radar'},
        {type: 'doc', id: 'project/eundo-content-studio', label: 'Eundo Content Studio'},
        {type: 'doc', id: 'project/reread-bookshelf', label: 'Reread Bookshelf'},
        {type: 'doc', id: 'project/portfolio-site', label: 'eundo.today'},
      ],
    },
    {
      type: 'category',
      label: 'In Progress',
      collapsed: false,
      items: [
        {type: 'doc', id: 'project/anjeuljido', label: 'Anjeuljido'},
        {type: 'doc', id: 'project/prompt-coach', label: 'Prompt Coach'},
        {type: 'doc', id: 'project/point-switch', label: 'Point Switch'},
        {type: 'doc', id: 'project/lunch-networking', label: 'Lunch Networking'},
      ],
    },
  ],
  bookSidebar: [{type: 'autogenerated', dirName: 'book'}],
};

module.exports = sidebars;
