// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  aboutMeSidebar: [{type: 'autogenerated', dirName: 'aboutMe'}],
  tilSidebar: [{type: 'autogenerated', dirName: 'til'}],
  projectSidebar: [{type: 'autogenerated', dirName: 'project'}],
  bookSidebar: [{type: 'autogenerated', dirName: 'book'}],
};

module.exports = sidebars;
