// @ts-check

const fs = require('fs');
const path = require('path');

const sidebarsFile = path.join(__dirname, 'sidebars.js');

const content = `// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  aboutMeSidebar: [{type: 'autogenerated', dirName: 'aboutMe'}],
  tilSidebar: [{type: 'autogenerated', dirName: 'til'}],
  projectSidebar: [{type: 'autogenerated', dirName: 'project'}],
  bookSidebar: [{type: 'autogenerated', dirName: 'book'}],
};

module.exports = sidebars;
`;

fs.writeFileSync(sidebarsFile, content, 'utf8');
console.log(`Updated ${path.relative(process.cwd(), sidebarsFile)}`);
