backend:
  name: github
  repo: eundo/TIL
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "dev_story"
    label: "Stories"
    folder: "blog/dev-story"
    create: true
    extension: "mdx"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Authors", name: "authors", widget: "list", default: ["eundo"] }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
