backend:
  name: github
  repo: eundo/TIL
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "dev_story"
    label: "Dev Story"
    folder: "blog/dev-story"
    create: true
    extension: "mdx"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "list", default: ["eundo"] }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "mdx" }
